name: CI (clang-libcxx-23)

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build-musl-clang.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/build-musl-clang.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  clang-libcxx-23:
    runs-on: ubuntu-24.04
    container: "debian:sid"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6

      - name: Build Dependencies
        id: build_depends
        run: |
          apt update
          apt install -y clang-23 libc++-23-dev libc++abi-23-dev cmake

      - name: Default to Clang
        run: |
          echo "CC=clang-23" >> "$GITHUB_ENV"
          echo "CXX=clang++-23" >> "$GITHUB_ENV"

      - name: Build
        id: cmake_build
        run: |
          cmake -B build \
            -DGGML_NATIVE=OFF \
            -DLLAMA_FATAL_WARNINGS=ON \
            -DGGML_RPC=ON \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++"
          cmake --build build --config Release -j $(nproc)
